# Top menu
menu:
  # About: /about

# Camera icon for website
baseurl:

# Default post title
default_post_title: Halo

#Date Format
date_format: YYYY 年 MM 月 DD 日

# Comment.
comments:
  # Disqus comment
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Register service worker
service_worker: false

# Local search with atom.xml, dependency hexo-generator-feed plugin
local_search: true

# using viewer.js to view image
# https://fengyuanchen.github.io/viewerjs/
image_viewer: true

# Table of content
# Maybe support more toc style in future.
toc:
  enable: true

# using highlight.js to show the code
# https://highlightjs.org/
hljs:
  enable: true
  theme: xcode
