# Top menu
# 顶端导航栏
menu:
  # 关于我: /about
  # Tags: /tags
  # Categories: /categories

# Default post title
default_post_title: Halo

#Date Format
date_format: YYYY 年 MM 月 DD 日

# Comment. 
comments:
  # Disqus comment
  # 使用 Disqus 作你的评论系统
  disqus:
    enable: false
    disqus_shortname:
  # Valine Comment
  # You need to follow https://valine.js.org/quickstart.html to get an appID and an appKey
  # 使用 Valine 作你的评论系统
  # 你需要按照 https://valine.js.org/quickstart.html 的方法获得一个 appID 和一个 appKey
  valine:
    enable: true
    appId: 
    appKey: 
    placeholder:  # 评论框占位符(留空默认启用一言 api 获取)

# Google Analytics Tracking ID
google_analytics: 

# Register service worker
service_worker: false

# Local search with atom.xml, dependency hexo-generator-feed plugin
local_search: true

# using viewer.js to view image
# https://fengyuanchen.github.io/viewerjs/
image_viewer: true

# using highlight.js to show the code
# https://highlightjs.org/
hljs:
  enable: true
  theme: xcode
