# Top menu
menu:
  # Tags: /tags
  # Categories: /categories 

# Site Icon
favicon: 

# Camera icon for website
baseurl:

# Default post title
default_post_title: Halo

#Date Format
date_format: YYYY 年 MM 月 DD 日

# Comment.
comments:
  # Disqus comment
  disqus:
    enable: false
    disqus_shortname:
  valine:
    enable: true
    appId: appid
    appKey: appkey
    placeholder: random # Placeholder. Set to random string if you want to have random placeholders(一言api). 
    
# Google Analytics Tracking ID
google_analytics:

# Register service worker
service_worker: false

# Local search with atom.xml, dependency hexo-generator-feed plugin
local_search: true

# using viewer.js to view image
# https://fengyuanchen.github.io/viewerjs/
image_viewer: true

# Table of content
# Maybe support more toc style in future.
toc:
  enable: true

footer:
  enable: true
  beian: 浙ICP备2022036129号-2
  # content: 本站采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh">CC BY-NC-SA 4.0</a> 协议进行许可

# using highlight.js to show the code
# https://highlightjs.org/
hljs:
  enable: true
  theme: atom-one-dark
